import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/controls/OrbitControls.js';
const scene=new THREE.Scene();scene.background=new THREE.Color(0x111b2c);scene.fog=new THREE.FogExp2(0x111b2c,.009);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,600);camera.position.set(17,9,18);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableZoom=false;controls.maxPolarAngle=Math.PI/2.3;controls.minPolarAngle=.7;controls.target.set(0,1,0);
scene.add(new THREE.HemisphereLight(0x8cb9ff,0x24301f,1.6));const sun=new THREE.DirectionalLight(0xffd5a8,2.2);sun.position.set(-25,35,15);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const world=new THREE.Group();scene.add(world);const shops=[];const coins=[];const npcs=[];const vehicles=[];
function mat(c,rough=.7,metal=0){return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal})}function box(w,h,d,c,x,y,z,rough=.7){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c,rough));o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;world.add(o);return o}function cyl(r,h,c,x,y,z){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,16),mat(c));o.position.set(x,y,z);o.castShadow=true;world.add(o);return o}
function sign(text,c,x,y,z){const cv=document.createElement('canvas');cv.width=700;cv.height=150;const ctx=cv.getContext('2d');ctx.fillStyle='#10151e';ctx.fillRect(0,0,700,150);ctx.fillStyle='#'+c.toString(16).padStart(6,'0');ctx.font='900 70px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,350,78);const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(cv),transparent:true}));sp.scale.set(6,1.28,1);sp.position.set(x,y,z);world.add(sp)}
// Avenue
box(70,.22,20,0x20262f,0,-.12,0);box(70,.28,8,0x606a74,0,.06,0);for(let x=-32;x<33;x+=6)box(2.7,.035,.22,0xe8dfc9,x,.22,0);box(70,.45,2.8,0x858e98,0,.18,11);box(70,.45,2.8,0x858e98,0,.18,-11);
function store(x,z,name,color){box(10,8,8,0x29323d,x,4,z);box(10.2,.6,8.2,0x0d1219,x,8.3,z);box(8,5,.18,0x8fa0aa,x,2.7,z-4.1,.25);sign(name,color,x,7.15,z-4.25);shops.push({x,z,name});return{x,z}}
store(-15,-3,'FASHION',0xff3ca8);store(0,-3,'URBAN',0x42a5ff);store(15,-3,'MESSY',0xff3ca8);store(-15,13,'SHOES',0x48e0a0);store(15,13,'SAVYS',0xf18fbf);
// building wings and windows
for(let x=-32;x<=32;x+=8){if(Math.abs(x)<20)continue;let h=10+((x*x)%17);box(6,h,6,0x182332,x,h/2,-16);box(6,h*.8,6,0x202b39,x,h*.4,16);for(let y=3;y<h-1;y+=3){box(2.3,1.1,.08,0x5e89aa,x,y,-19.05);box(2.3,1.1,.08,0x496b87,x,y,19.05)}}
function tree(x,z){cyl(.3,3,0x533b2a,x,1.5,z);const g=new THREE.Mesh(new THREE.IcosahedronGeometry(1.7,1),mat(0x2e784b,1));g.position.set(x,4,z);g.castShadow=true;world.add(g)}function lamp(x,z){cyl(.09,4,0x141922,x,2,z);const l=new THREE.PointLight(0xffb56c,4.5,12);l.position.set(x,4,z);scene.add(l)}for(let x=-30;x<=30;x+=10){tree(x,8);tree(x,-8);lamp(x,8);lamp(x,-8)}
// storefront interiors visible through fronts
function shelf(x,z,c){box(2.4,2,.45,0x151a22,x,1.4,z);for(let i=-2;i<=2;i++)box(.25,.8,.3,c,x+i*.45,2.15,z-.2)}for(let x=-17;-20<x&&x<-11;x+=2)shelf(x,-7,0xff3ca8);for(let x=-2;x<=2;x+=2)shelf(x,-7,0x42a5ff);for(let x=13;x<=17;x+=2)shelf(x,-7,0xff3ca8);
// player
const player=new THREE.Group();world.add(player);let skin=0xc68d70;let body=box(.9,1.55,.55,0x101317,0,1.05,0);let head=new THREE.Mesh(new THREE.SphereGeometry(.38,20,16),mat(skin,.75));head.position.set(0,2.12,0);head.castShadow=true;player.add(head);let top=box(1.05,1.2,.62,0x11151d,0,1.35,0);player.add(top);let l1=box(.34,1.1,.4,0x161b23,-.28,.48,0),l2=box(.34,1.1,.4,0x161b23,.28,.48,0);player.add(l1,l2);player.position.set(0,0,7);
function setOutfit(type){const colors={street:[0x10131a,0x195eaa],sport:[0x8e1f2c,0x111317],casual:[0xa7abb2,0xf0f0ed]};const [a,b]=colors[type];top.material.color.setHex(a);l1.material.color.setHex(b);l2.material.color.setHex(b);}
let coinsCollected=0,money=250,visited=false,outfit=false,foundShoes=false,near=null;function coin(x,z){const c=new THREE.Mesh(new THREE.CylinderGeometry(.3,.3,.13,24),mat(0xffd43b,.25,.8));c.rotation.x=Math.PI/2;c.position.set(x,.75,z);world.add(c);coins.push(c)}[[-22,5],[-18,2],[-12,6],[-7,-5],[-2,4],[4,-4],[10,5],[18,7],[23,-5],[28,4]].forEach(p=>coin(...p));
function npc(x,z,dx){const g=new THREE.Group();const shirt=[0x2b5ca8,0xff4b8b,0x2d9a71,0xe5a63c][Math.floor(Math.random()*4)];const b=new THREE.Mesh(new THREE.CylinderGeometry(.25,.32,1.2,10),mat(shirt));b.position.y=1;g.add(b);const h=new THREE.Mesh(new THREE.SphereGeometry(.28,12,10),mat(0xc68d70));h.position.y=1.82;g.add(h);g.position.set(x,0,z);g.userData.v=dx;world.add(g);npcs.push(g)}for(let i=0;i<14;i++)npc(-28+Math.random()*56,-8+Math.random()*16,(Math.random()>.5?1:-1)*(.5+Math.random()));
function car(x,z,c,spd){const g=new THREE.Group();const base=new THREE.Mesh(new THREE.BoxGeometry(2.7,.65,1.35),mat(c,.35,.15));base.position.y=.6;g.add(base);const topc=new THREE.Mesh(new THREE.BoxGeometry(1.5,.55,1.1),mat(0x273241,.2,.1));topc.position.set(0,1.05,0);g.add(topc);g.position.set(x,.1,z);g.userData.spd=spd;world.add(g);vehicles.push(g)}car(-28,-3,0xd83b42,.08);car(28,3,0x2d72c8,-.09);car(5,2,0xf0b72e,.07);
function mission(){document.querySelector('#m1').classList.toggle('done',visited);document.querySelector('#m1').textContent=(visited?'✓ ':'○ ')+'Visit the Fashion Store';document.querySelector('#m2').classList.toggle('done',coinsCollected>=8);document.querySelector('#m2').textContent=(coinsCollected>=8?'✓ ':'○ ')+'Collect 8 Coins';document.querySelector('#m3').classList.toggle('done',outfit);document.querySelector('#m3').textContent=(outfit?'✓ ':'○ ')+'Buy a Street Outfit';document.querySelector('#m4').classList.toggle('done',foundShoes);document.querySelector('#m4').textContent=(foundShoes?'✓ ':'○ ')+'Find the Shoe Store';if(visited&&coinsCollected>=8&&outfit&&foundShoes)document.querySelector('#complete').style.display='flex'}
function interact(){if(!near)return;if(near.name==='FASHION'&&!visited){visited=true;document.querySelector('#outfitMenu').style.display='flex'}else if(near.name==='SHOES'&&!foundShoes){foundShoes=true}mission()}
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e')interact()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);document.querySelectorAll('[data-outfit]').forEach(b=>b.onclick=()=>{setOutfit(b.dataset.outfit);outfit=true;money-=50;document.querySelector('#money').textContent=money;document.querySelector('#outfitMenu').style.display='none';mission()});document.querySelector('#closeWardrobe').onclick=()=>document.querySelector('#outfitMenu').style.display='none';
function checkNear(){near=null;let best=999;for(const s of shops){const d=Math.hypot(player.position.x-s.x,player.position.z-s.z);if(d<best){best=d;near=s}}const p=document.querySelector('#shopPrompt');if(near&&best<6){p.style.display='block';p.innerHTML='<span class="key">E</span> '+(near.name==='FASHION'&&!visited?'Enter Fashion Store':near.name==='SHOES'&&!foundShoes?'Enter Shoe Store':'Explore '+near.name)}else p.style.display='none'}
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);let dx=0,dz=0;if(keys.w||keys.arrowup)dz-=1;if(keys.s||keys.arrowdown)dz+=1;if(keys.a||keys.arrowleft)dx-=1;if(keys.d||keys.arrowright)dx+=1;const len=Math.hypot(dx,dz)||1;const speed=(keys.shift?8:4.2)*dt;if(dx||dz){player.position.x+=dx/len*speed;player.position.z+=dz/len*speed;player.rotation.y=Math.atan2(dx,dz)}player.position.x=THREE.MathUtils.clamp(player.position.x,-32,32);player.position.z=THREE.MathUtils.clamp(player.position.z,-9,9);
for(const c of coins){c.rotation.z+=dt*3;if(c.visible&&c.position.distanceTo(player.position)<1.15){c.visible=false;coinsCollected++;document.querySelector('#coins').textContent=coinsCollected;mission()}}for(const n of npcs){n.position.x+=n.userData.v*dt;if(n.position.x>34)n.position.x=-34;if(n.position.x<-34)n.position.x=34;n.rotation.y=n.userData.v>0?Math.PI/2:-Math.PI/2}for(const v of vehicles){v.position.x+=v.userData.spd*30*dt;if(v.position.x>38)v.position.x=-38;if(v.position.x<-38)v.position.x=38}
checkNear();camera.position.lerp(new THREE.Vector3(player.position.x+11,8.5,player.position.z+13),.075);controls.target.lerp(new THREE.Vector3(player.position.x,1,player.position.z),.12);controls.update();renderer.render(scene,camera)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
