import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/controls/OrbitControls.js';
const scene=new THREE.Scene();scene.background=new THREE.Color(0x24182b);scene.fog=new THREE.FogExp2(0x24182b,.010);const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,700);camera.position.set(15,9,18);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableZoom=false;controls.maxPolarAngle=Math.PI/2.25;controls.minPolarAngle=.65;controls.target.set(0,1,0);scene.add(new THREE.HemisphereLight(0xffb8dc,0x251a2d,1.7));const moon=new THREE.DirectionalLight(0xffd5ef,2.5);moon.position.set(-20,35,12);moon.castShadow=true;moon.shadow.mapSize.set(2048,2048);scene.add(moon);
const world=new THREE.Group();scene.add(world);const stalls=[],coins=[],npcs=[],cars=[];function M(c,r=.7,m=0){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m})}function box(w,h,d,c,x,y,z,r=.7){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),M(c,r));o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;world.add(o);return o}function cyl(r,h,c,x,y,z){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,14),M(c));o.position.set(x,y,z);o.castShadow=true;world.add(o);return o}function label(t,c,x,y,z,s=4){const cv=document.createElement('canvas');cv.width=700;cv.height=150;const q=cv.getContext('2d');q.fillStyle='#17131d';q.fillRect(0,0,700,150);q.fillStyle='#'+c.toString(16).padStart(6,'0');q.font='900 65px Arial';q.textAlign='center';q.textBaseline='middle';q.fillText(t,350,76);const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(cv),transparent:true}));sp.scale.set(s,0.86,1);sp.position.set(x,y,z);world.add(sp)}
// bazaar ground, lanes and stalls
box(82,.2,30,0x17151c,0,-.12,0);box(82,.25,5,0x6d6670,0,.05,0);for(let x=-38;x<39;x+=5)box(2.2,.03,.16,0xe7c76d,x,.22,0);box(82,.35,3,0x8d7f72,0,.18,14);box(82,.35,3,0x8d7f72,0,.18,-14);
function stall(x,z,name,c){box(9,4.8,5,0x493b45,x,2.4,z);box(9.4,.35,5.4,c,x,4.95,z);label(name,c,x,4.25,z-2.65,4.5);for(let i=-3;i<=3;i+=1.5)box(.7,1.5,.8,c,x+i,1.1,z-2.8,.4);stalls.push({x,z,name})}
stall(-25,-7,'TEXTILES',0xff6b9f);stall(-13,-7,'ACCESSORIES',0x53b9ff);stall(0,-7,'FESTIVAL',0xffb52e);stall(13,-7,'SNEAKERS',0x58e5a4);stall(26,-7,'SAVYS',0xf18fbf);stall(-25,7,'FOOD',0xff795f);stall(-10,7,'GIFTS',0x9c7bff);stall(8,7,'VINTAGE',0xd6a15e);stall(24,7,'SECRET',0x55eaff);
// arch, banners, awnings
for(let x=-36;x<=36;x+=12){box(.35,5,.35,0x19151e,x,2.5,-13);box(.35,5,.35,0x19151e,x,2.5,13);box(2.5,.22,.3,0xff3ca8,x,5.1,-13);box(2.5,.22,.3,0x53b9ff,x,5.1,13)}
function tree(x,z){cyl(.28,2.8,0x4b3025,x,1.4,z);const g=new THREE.Mesh(new THREE.IcosahedronGeometry(1.45,1),M(0x28734a));g.position.set(x,3.7,z);world.add(g)}function lamp(x,z){cyl(.08,4,0x14141a,x,2,z);const p=new THREE.PointLight(0xff9ed5,5,12);p.position.set(x,4,z);scene.add(p)}for(let x=-35;x<=35;x+=9){tree(x,11);tree(x,-11);lamp(x,11);lamp(x,-11)}
// player
const player=new THREE.Group();world.add(player);let top=box(1.05,1.2,.62,0x12151d,0,1.35,0),leg1=box(.34,1.1,.4,0x151820,-.28,.48,0),leg2=box(.34,1.1,.4,0x151820,.28,.48,0);player.add(top,leg1,leg2);const head=new THREE.Mesh(new THREE.SphereGeometry(.38,20,16),M(0xc68d70));head.position.y=2.12;head.castShadow=true;player.add(head);player.position.set(0,0,12);
function outfit(t){const a={street:[0x10131a,0x2b5ca8],festival:[0x7c1fff,0xffb52e],summer:[0x22a7bb,0xf2eee7]}[t];top.material.color.setHex(a[0]);leg1.material.color.setHex(a[1]);leg2.material.color.setHex(a[1])}
let coinCount=0,money=400,visited=false,bought=false,secret=false,near=null;function coin(x,z){const c=new THREE.Mesh(new THREE.CylinderGeometry(.28,.28,.13,24),M(0xffd43b,.2,.8));c.rotation.x=Math.PI/2;c.position.set(x,.7,z);world.add(c);coins.push(c)}[[-33,-4],[-27,3],[-20,-2],[-15,5],[-9,-3],[-4,4],[2,-4],[7,3],[13,-2],[19,5],[27,-3],[34,4]].forEach(p=>coin(...p));
function npc(x,z,v){const g=new THREE.Group();const colors=[0x2b5ca8,0xff4b8b,0x2d9a71,0xe5a63c,0x9b6cff];const b=new THREE.Mesh(new THREE.CylinderGeometry(.24,.31,1.2,10),M(colors[Math.floor(Math.random()*colors.length)]));b.position.y=1;g.add(b);const h=new THREE.Mesh(new THREE.SphereGeometry(.27,12,10),M(0xc68d70));h.position.y=1.82;g.add(h);g.position.set(x,0,z);g.userData.v=v;world.add(g);npcs.push(g)}for(let i=0;i<20;i++)npc(-39+Math.random()*78,-9+Math.random()*18,(Math.random()>.5?1:-1)*(.45+Math.random()*.6));
function car(x,z,c,v){const g=new THREE.Group();const b=new THREE.Mesh(new THREE.BoxGeometry(2.8,.65,1.3),M(c,.35,.15));b.position.y=.6;g.add(b);const roof=new THREE.Mesh(new THREE.BoxGeometry(1.4,.5,1),M(0x252936,.2));roof.position.y=1.02;g.add(roof);g.position.set(x,.1,z);g.userData.v=v;world.add(g);cars.push(g)}car(-35,-2,0xffbd2e,.09);car(35,2,0x48a9ff,-.08);car(0,2,0xf04f72,.07);
function mission(){m1.textContent=(visited?'✓ ':'○ ')+'Visit the Bazaar';m2.textContent=(coinCount>=10?'✓ ':'○ ')+'Collect 10 Coins';m3.textContent=(bought?'✓ ':'○ ')+'Buy a Festival Outfit';m4.textContent=(secret?'✓ ':'○ ')+'Find the Secret Stall';[m1,m2,m3,m4].forEach((e,i)=>e.classList.toggle('done',[visited,coinCount>=10,bought,secret][i]));if(visited&&coinCount>=10&&bought&&secret)complete.style.display='flex'}
function interact(){if(!near)return;if(near.name==='FESTIVAL'&&!bought){visited=true;outfitMenu.style.display='flex'}if(near.name==='SECRET'&&!secret){secret=true;money+=150}mission()}
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e')interact()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);document.querySelectorAll('[data-outfit]').forEach(b=>b.onclick=()=>{outfit(b.dataset.outfit);bought=true;money-=80;document.querySelector('#money').textContent=money;outfitMenu.style.display='none';mission()});close.onclick=()=>outfitMenu.style.display='none';
function nearCheck(){near=null;let d0=999;for(const s of stalls){const d=Math.hypot(player.position.x-s.x,player.position.z-s.z);if(d<d0){d0=d;near=s}}if(near&&d0<6){prompt.style.display='block';prompt.innerHTML='<span class="key">E</span> '+(near.name==='FESTIVAL'&&!bought?'Enter Festival Stall':near.name==='SECRET'&&!secret?'Investigate Secret Stall':'Explore '+near.name)}else prompt.style.display='none'}
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);let x=0,z=0;if(keys.w||keys.arrowup)z--;if(keys.s||keys.arrowdown)z++;if(keys.a||keys.arrowleft)x--;if(keys.d||keys.arrowright)x++;const len=Math.hypot(x,z)||1;if(x||z){const sp=(keys.shift?8:4.5)*dt;player.position.x+=x/len*sp;player.position.z+=z/len*sp;player.rotation.y=Math.atan2(x,z)}player.position.x=THREE.MathUtils.clamp(player.position.x,-39,39);player.position.z=THREE.MathUtils.clamp(player.position.z,-12,12);for(const c of coins){c.rotation.z+=dt*3;if(c.visible&&c.position.distanceTo(player.position)<1.1){c.visible=false;coinCount++;coinsEl.textContent=coinCount;mission()}}for(const n of npcs){n.position.x+=n.userData.v*dt;if(n.position.x>42)n.position.x=-42;if(n.position.x<-42)n.position.x=42}for(const v of cars){v.position.x+=v.userData.v*30*dt;if(v.position.x>45)v.position.x=-45;if(v.position.x<-45)v.position.x=45}nearCheck();camera.position.lerp(new THREE.Vector3(player.position.x+11,8.8,player.position.z+15),.075);controls.target.lerp(new THREE.Vector3(player.position.x,1,player.position.z),.12);controls.update();renderer.render(scene,camera)}const coinsEl=document.querySelector('#coins');animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
